import {
  Project,
  UserProfile,
  ProjectApplication,
  PaymentMethod,
  ContributorEarning,
  WithdrawalRequest,
  ProjectUpdate,
  NotificationItem,
} from './types';

// Real active projects: French → English Machine Translation and Arabic → English Translation
export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'proj-french-en-002',
    name: 'French → English Machine Translation Project',
    category: 'Translation & Localization',
    projectType: 'Translation / AI Data',
    description:
      'High-volume machine translation post-editing (MTPE), cultural localization, and linguistic quality assessment for French to English textual corpora, conversation logs, and domain-specific documentation. Contributors evaluate fluency, terminological accuracy, and grammatical precision.',
    language: 'French',
    sourceLanguage: 'French',
    targetLanguage: 'English',
    country: 'Global',
    skillsRequired: [
      'Bilingual French/English',
      'Machine Translation Post-Editing (MTPE)',
      'Localization QA',
      'Context Evaluation',
    ],
    requiredContributors: 4000,
    approvedContributors: 2,
    startDate: '2026-09-05',
    endDate: '2027-08-31',
    applicationDeadline: '2026-11-30',
    qualificationRequired: true,
    qualificationTestInfo:
      '15-minute French to English translation evaluation and terminology verification benchmark.',
    minimumRequirement:
      'Native or C1/C2 French proficiency with professional fluency in written English.',
    instructions:
      'Post-edit machine-translated French sentences into idiomatic, accurate English conforming to domain glossaries and quality rubrics.',
    communityLink: 'https://community.nexora.work/c/french-english-translation',
    announcement:
      'The French → English Machine Translation Project is currently welcoming applications worldwide.',
    status: 'Open',
    paymentType: 'Per Item',
    paymentRateType: 'range',
    paymentAmountMin: 0.8,
    paymentAmountMax: 3.0,
    ratePay: '$0.80 - $3 / item',
    createdAt: '2026-09-05',
  },
  {
    id: 'proj-arabic-en-001',
    name: 'Arabic → English Translation Project',
    category: 'Translation & Localization',
    projectType: 'Translation / AI Data',
    description:
      'Translation, localization, and quality review of high-value textual content, conversational datasets, and technical documentation from Modern Standard Arabic and regional dialects into fluent English. Contributors assess translation accuracy, grammatical fidelity, terminological precision, and cultural nuance.',
    language: 'Arabic, English',
    sourceLanguage: 'Arabic',
    targetLanguage: 'English',
    country: 'Global',
    skillsRequired: [
      'Bilingual Arabic/English',
      'Modern Standard Arabic (MSA)',
      'Context Checking',
      'Terminology Research',
      'Localization QA',
    ],
    requiredContributors: 1200,
    approvedContributors: 4,
    startDate: '2026-09-15',
    endDate: '2027-06-30',
    applicationDeadline: '2026-10-15',
    qualificationRequired: true,
    qualificationTestInfo:
      'Brief 15-minute bilingual Arabic to English translation evaluation and terminology verification benchmark.',
    minimumRequirement:
      'Native or C1/C2 Arabic proficiency and professional fluency in written English.',
    instructions:
      'Translate source Arabic passages into natural, grammatically sound English. Adhere strictly to domain glossaries, maintain cultural context, and flag ambiguous idiomatic phrasing.',
    communityLink: 'https://community.nexora.work/c/arabic-english-translation',
    announcement:
      'The Arabic → English Translation Project is officially open for applications. Complete your contributor profile and apply to schedule your qualification benchmark.',
    status: 'Open',
    paymentType: 'Per Item',
    paymentRateType: 'range',
    paymentAmountMin: 0.3,
    paymentAmountMax: 0.7,
    ratePay: '$0.30 - $0.70 / item',
    createdAt: '2026-09-01',
  },
];

export const INITIAL_USERS: UserProfile[] = [
  {
    id: 'adm-001',
    firstName: 'Muhammad',
    lastName: 'Ayan',
    email: '03004292351muhammadayan@gmail.com',
    role: 'admin',
    isEmailVerified: true,
    profileStatus: 'Complete',
    avatar: 'MA',
    country: 'Global',
    languages: ['English', 'Arabic'],
    languageProficiency: {
      English: 'Native / Fluent',
      Arabic: 'Professional Working',
    },
    skills: ['Workforce Operations', 'Quality Assurance', 'Project Architecture'],
    experience: 'Platform Administrator & Operations Director at Nexora Workforce',
    status: 'active',
    createdAt: '2026-09-01',
    phone: '',
  },
  {
    id: 'usr-eg-8821',
    firstName: 'Omar',
    lastName: 'Hassan',
    email: 'omar.hassan.trans@gmail.com',
    phone: '+20 100 234 5678',
    country: 'Egypt',
    languages: ['Arabic', 'English'],
    languageProficiency: {
      Arabic: 'Native / Fluent',
      English: 'Professional Working',
    },
    skills: [
      'Bilingual Arabic/English',
      'Modern Standard Arabic (MSA)',
      'Localization QA',
      'Egyptian Dialect',
    ],
    experience: 'Senior Arabic-English Translator & Localization Specialist with 5 years experience in Cairo.',
    role: 'contributor',
    isEmailVerified: true,
    profileStatus: 'Complete',
    avatar: 'OH',
    status: 'active',
    createdAt: '2026-09-07',
  },
  {
    id: 'usr-eg-8822',
    firstName: 'Nour',
    lastName: 'Mahmoud',
    email: 'nour.mahmoud.eg@gmail.com',
    phone: '+20 112 345 6789',
    country: 'Egypt',
    languages: ['Arabic', 'English'],
    languageProficiency: {
      Arabic: 'Native / Fluent',
      English: 'Professional Working',
    },
    skills: [
      'Arabic Translation',
      'Terminology Research',
      'Proofreading',
      'Machine Translation Review',
    ],
    experience: 'Linguistics graduate from Cairo University. 3 years freelance translation and data annotation.',
    role: 'contributor',
    isEmailVerified: true,
    profileStatus: 'Complete',
    avatar: 'NM',
    status: 'active',
    createdAt: '2026-09-07',
  },
  {
    id: 'usr-eg-8823',
    firstName: 'Mariam',
    lastName: 'Farouk',
    email: 'mariam.farouk.cairo@gmail.com',
    phone: '+20 122 456 7890',
    country: 'Egypt',
    languages: ['Arabic', 'English'],
    languageProficiency: {
      Arabic: 'Native / Fluent',
      English: 'Native / Fluent',
    },
    skills: [
      'Localization QA',
      'Subtitling',
      'Audio Transcription',
      'MSA Translation',
    ],
    experience: 'Bilingual translator and language quality evaluator based in Giza, Egypt.',
    role: 'contributor',
    isEmailVerified: true,
    profileStatus: 'Complete',
    avatar: 'MF',
    status: 'active',
    createdAt: '2026-09-07',
  },
  {
    id: 'usr-ke-1001',
    firstName: 'David',
    lastName: 'Ochieng',
    email: 'david.ochieng.nbo@gmail.com',
    phone: '+254 712 345 678',
    country: 'Kenya',
    languages: ['English', 'Swahili'],
    languageProficiency: {
      English: 'Native / Fluent',
      Swahili: 'Native / Fluent',
    },
    skills: [
      'Translation & Localization',
      'AI Data Collection',
      'Audio Annotation',
      'Transcription',
    ],
    experience: 'Bilingual Swahili-English linguist and AI training data annotator in Nairobi, Kenya.',
    role: 'contributor',
    isEmailVerified: true,
    profileStatus: 'Complete',
    avatar: 'DO',
    status: 'active',
    createdAt: '2026-09-06',
  },
  {
    id: 'usr-ke-1002',
    firstName: 'Faith',
    lastName: 'Mwangi',
    email: 'faith.mwangi.ling@gmail.com',
    phone: '+254 722 890 123',
    country: 'Kenya',
    languages: ['English', 'Swahili'],
    languageProficiency: {
      English: 'Native / Fluent',
      Swahili: 'Native / Fluent',
    },
    skills: [
      'Audio Annotation',
      'Transcription',
      'Content Evaluation',
      'Data QA',
    ],
    experience: 'Speech dataset contributor and professional transcriber based in Mombasa, Kenya.',
    role: 'contributor',
    isEmailVerified: true,
    profileStatus: 'Complete',
    avatar: 'FM',
    status: 'active',
    createdAt: '2026-09-06',
  },
  {
    id: 'usr-sa-2001',
    firstName: 'Abdulaziz',
    lastName: 'Al-Zahrani',
    email: 'abdulaziz.zahrani@gmail.com',
    phone: '+966 50 123 4567',
    country: 'Saudi Arabia',
    languages: ['Arabic', 'English'],
    languageProficiency: {
      Arabic: 'Native / Fluent',
      English: 'Professional Working',
    },
    skills: [
      'Modern Standard Arabic (MSA)',
      'Bilingual Arabic/English',
      'Terminology Research',
      'Localization QA',
    ],
    experience: 'Linguistic reviewer and MTPE specialist in Riyadh, Saudi Arabia. King Saud University alumnus.',
    role: 'contributor',
    isEmailVerified: true,
    profileStatus: 'Complete',
    avatar: 'AZ',
    status: 'active',
    createdAt: '2026-09-05',
  },
  {
    id: 'usr-sa-2002',
    firstName: 'Reem',
    lastName: 'Al-Ghamdi',
    email: 'reem.ghamdi.trans@gmail.com',
    phone: '+966 55 987 6543',
    country: 'Saudi Arabia',
    languages: ['Arabic', 'English'],
    languageProficiency: {
      Arabic: 'Native / Fluent',
      English: 'Professional Working',
    },
    skills: [
      'Arabic Translation',
      'Context Checking',
      'AI Prompt Evaluation',
      'Quality Assurance',
    ],
    experience: 'Freelance translator & cultural consultant in Jeddah, Saudi Arabia. 4 years enterprise localization experience.',
    role: 'contributor',
    isEmailVerified: true,
    profileStatus: 'Complete',
    avatar: 'RG',
    status: 'active',
    createdAt: '2026-09-05',
  },
  {
    id: 'usr-pk-3001',
    firstName: 'Ayan',
    lastName: 'Khalid',
    email: 'saimaanjum650@gmail.com',
    phone: '+92 300 429 2351',
    country: 'Pakistan',
    languages: ['English', 'Urdu'],
    languageProficiency: {
      English: 'Native / Fluent',
      Urdu: 'Native / Fluent',
    },
    skills: [
      'Translation & Localization',
      'Workforce Coordination',
      'Dataset Verification',
    ],
    experience: 'Independent Contributor & Regional Workforce Coordinator in Pakistan.',
    role: 'contributor',
    isEmailVerified: true,
    profileStatus: 'Complete',
    avatar: 'AK',
    status: 'active',
    createdAt: '2026-09-07',
  },
  {
    id: 'usr-pk-3002',
    firstName: 'Muhammad',
    lastName: 'Hamza',
    email: 'm.hamza.pk@gmail.com',
    phone: '+92 315 789 4561',
    country: 'Pakistan',
    languages: ['English', 'Urdu'],
    languageProficiency: {
      English: 'Professional Working',
      Urdu: 'Native / Fluent',
    },
    skills: ['AI Data Collection', 'Audio Transcription', 'Text Annotation'],
    experience: 'Computer Science student and crowd data annotator in Lahore, Pakistan.',
    role: 'contributor',
    isEmailVerified: true,
    profileStatus: 'Complete',
    avatar: 'MH',
    status: 'active',
    createdAt: '2026-09-06',
  },
  {
    id: 'usr-pk-3003',
    firstName: 'Zunaira',
    lastName: 'Tariq',
    email: 'zunaira.tariq.ling@gmail.com',
    phone: '+92 321 654 9870',
    country: 'Pakistan',
    languages: ['English', 'Urdu'],
    languageProficiency: {
      English: 'Native / Fluent',
      Urdu: 'Native / Fluent',
    },
    skills: [
      'Text Annotation',
      'Content Evaluation',
      'Sentiment Analysis',
      'Transcription',
    ],
    experience: 'Linguist with 3 years experience in multilingual NLP datasets and sentiment tagging in Islamabad.',
    role: 'contributor',
    isEmailVerified: true,
    profileStatus: 'Complete',
    avatar: 'ZT',
    status: 'active',
    createdAt: '2026-09-06',
  },
  {
    id: 'usr-in-4001',
    firstName: 'Aarav',
    lastName: 'Sharma',
    email: 'aarav.sharma.nlp@gmail.com',
    phone: '+91 98765 43210',
    country: 'India',
    languages: ['English', 'Hindi'],
    languageProficiency: {
      English: 'Native / Fluent',
      Hindi: 'Native / Fluent',
    },
    skills: [
      'Translation & Localization',
      'Machine Translation Post-Editing (MTPE)',
      'AI Data Collection',
      'Context Evaluation',
    ],
    experience: 'NLP linguistic analyst and professional Hindi-English post-editor in Bengaluru, India.',
    role: 'contributor',
    isEmailVerified: true,
    profileStatus: 'Complete',
    avatar: 'AS',
    status: 'active',
    createdAt: '2026-09-05',
  },
  {
    id: 'usr-in-4002',
    firstName: 'Priya',
    lastName: 'Patel',
    email: 'priya.patel.ai@gmail.com',
    phone: '+91 98123 45678',
    country: 'India',
    languages: ['English', 'Hindi', 'Gujarati'],
    languageProficiency: {
      English: 'Native / Fluent',
      Hindi: 'Native / Fluent',
    },
    skills: [
      'Audio Annotation',
      'Transcription',
      'Localization QA',
      'Quality Assurance',
    ],
    experience: 'Speech-to-text evaluation specialist and multilingual transcriptionist based in Mumbai, India.',
    role: 'contributor',
    isEmailVerified: true,
    profileStatus: 'Complete',
    avatar: 'PP',
    status: 'active',
    createdAt: '2026-09-05',
  },
  {
    id: 'usr-ae-5001',
    firstName: 'Zaid',
    lastName: 'Al-Mansoor',
    email: 'zaid.mansoor.dxb@gmail.com',
    phone: '+971 50 123 4567',
    country: 'United Arab Emirates',
    languages: ['Arabic', 'English'],
    languageProficiency: {
      Arabic: 'Native / Fluent',
      English: 'Native / Fluent',
    },
    skills: [
      'Bilingual Arabic/English',
      'Quality Assurance',
      'Modern Standard Arabic (MSA)',
      'Localization QA',
    ],
    experience: 'Media & technical translation consultant in Dubai, UAE.',
    role: 'contributor',
    isEmailVerified: true,
    profileStatus: 'Complete',
    avatar: 'ZM',
    status: 'active',
    createdAt: '2026-09-05',
  },
  {
    id: 'usr-ng-6001',
    firstName: 'Chinedu',
    lastName: 'Okafor',
    email: 'chinedu.okafor.ai@gmail.com',
    phone: '+234 803 123 4567',
    country: 'Nigeria',
    languages: ['English', 'Yoruba', 'Igbo'],
    languageProficiency: {
      English: 'Native / Fluent',
    },
    skills: [
      'Audio Annotation',
      'Transcription',
      'AI Data Collection',
      'Speech Data Evaluation',
    ],
    experience: 'Acoustic data collector and transcription auditor in Lagos, Nigeria.',
    role: 'contributor',
    isEmailVerified: true,
    profileStatus: 'Complete',
    avatar: 'CO',
    status: 'active',
    createdAt: '2026-09-04',
  },
  {
    id: 'usr-ph-7001',
    firstName: 'Maria',
    lastName: 'Santos',
    email: 'maria.santos.trans@gmail.com',
    phone: '+63 917 123 4567',
    country: 'Philippines',
    languages: ['English', 'Tagalog'],
    languageProficiency: {
      English: 'Native / Fluent',
      Tagalog: 'Native / Fluent',
    },
    skills: [
      'Text Annotation',
      'Content Evaluation',
      'Transcription',
      'Quality Assurance',
    ],
    experience: 'Lead data annotator and English transcription reviewer in Manila, Philippines.',
    role: 'contributor',
    isEmailVerified: true,
    profileStatus: 'Complete',
    avatar: 'MS',
    status: 'active',
    createdAt: '2026-09-04',
  },
  {
    id: 'usr-fr-8001',
    firstName: 'Camille',
    lastName: 'Laurent',
    email: 'camille.laurent.lyon@gmail.com',
    phone: '+33 6 12 34 56 78',
    country: 'France',
    languages: ['French', 'English'],
    languageProficiency: {
      French: 'Native / Fluent',
      English: 'Native / Fluent',
    },
    skills: [
      'Bilingual French/English',
      'Machine Translation Post-Editing (MTPE)',
      'Localization QA',
      'Context Evaluation',
    ],
    experience: 'Certified French-English translator and MTPE quality specialist in Lyon, France.',
    role: 'contributor',
    isEmailVerified: true,
    profileStatus: 'Complete',
    avatar: 'CL',
    status: 'active',
    createdAt: '2026-09-03',
  },
  {
    id: 'usr-de-8002',
    firstName: 'Lukas',
    lastName: 'Weber',
    email: 'lukas.weber.berlin@gmail.com',
    phone: '+49 170 1234567',
    country: 'Germany',
    languages: ['German', 'English'],
    languageProficiency: {
      German: 'Native / Fluent',
      English: 'Native / Fluent',
    },
    skills: [
      'Translation & Localization',
      'Technical Translation',
      'Localization QA',
      'Terminology Research',
    ],
    experience: 'Technical translator and terminology researcher in Berlin, Germany.',
    role: 'contributor',
    isEmailVerified: true,
    profileStatus: 'Complete',
    avatar: 'LW',
    status: 'active',
    createdAt: '2026-09-03',
  },
  {
    id: 'usr-br-8003',
    firstName: 'Lucas',
    lastName: 'Silva',
    email: 'lucas.silva.sp@gmail.com',
    phone: '+55 11 98765-4321',
    country: 'Brazil',
    languages: ['Portuguese', 'English'],
    languageProficiency: {
      Portuguese: 'Native / Fluent',
      English: 'Professional Working',
    },
    skills: [
      'Translation & Localization',
      'Audio Annotation',
      'Text Annotation',
      'AI Data Collection',
    ],
    experience: 'Brazilian Portuguese linguistic specialist and data evaluator in São Paulo, Brazil.',
    role: 'contributor',
    isEmailVerified: true,
    profileStatus: 'Complete',
    avatar: 'LS',
    status: 'active',
    createdAt: '2026-09-02',
  },
  {
    id: 'usr-ca-8004',
    firstName: 'Liam',
    lastName: 'Tremblay',
    email: 'liam.tremblay.mtl@gmail.com',
    phone: '+1 514 123 4567',
    country: 'Canada',
    languages: ['English', 'French'],
    languageProficiency: {
      English: 'Native / Fluent',
      French: 'Native / Fluent',
    },
    skills: [
      'Bilingual French/English',
      'Machine Translation Post-Editing (MTPE)',
      'Localization QA',
    ],
    experience: 'Bilingual Canadian translator (English/French) and localization QA auditor in Montreal, Canada.',
    role: 'contributor',
    isEmailVerified: true,
    profileStatus: 'Complete',
    avatar: 'LT',
    status: 'active',
    createdAt: '2026-09-02',
  },
  {
    id: 'usr-ma-8005',
    firstName: 'Yassine',
    lastName: 'Berrada',
    email: 'yassine.berrada.casa@gmail.com',
    phone: '+212 661 123456',
    country: 'Morocco',
    languages: ['Arabic', 'French', 'English'],
    languageProficiency: {
      Arabic: 'Native / Fluent',
      French: 'Native / Fluent',
      English: 'Professional Working',
    },
    skills: [
      'Modern Standard Arabic (MSA)',
      'Bilingual Arabic/English',
      'Bilingual French/English',
      'Context Checking',
    ],
    experience: 'Trilingual translator in Casablanca, Morocco specializing in North African Arabic and French-English MTPE.',
    role: 'contributor',
    isEmailVerified: true,
    profileStatus: 'Complete',
    avatar: 'YB',
    status: 'active',
    createdAt: '2026-09-02',
  },
  {
    id: 'usr-us-9001',
    firstName: 'Marcus',
    lastName: 'Bennett',
    email: 'marcus.bennett.data@gmail.com',
    phone: '+1 512 555 0199',
    country: 'United States',
    languages: ['English', 'Spanish'],
    languageProficiency: {
      English: 'Native / Fluent',
      Spanish: 'Professional Working',
    },
    skills: [
      'Quality Assurance',
      'Content Evaluation',
      'AI Prompt Evaluation',
      'Text Annotation',
    ],
    experience: 'Senior Data Evaluation Specialist in Austin, Texas. 5+ years reviewing LLM RLHF corpora.',
    role: 'contributor',
    isEmailVerified: true,
    profileStatus: 'Complete',
    avatar: 'MB',
    status: 'active',
    createdAt: '2026-09-01',
  },
  {
    id: 'usr-uk-9002',
    firstName: 'Sophie',
    lastName: 'Taylor',
    email: 'sophie.taylor.uk@gmail.com',
    phone: '+44 20 7946 0912',
    country: 'United Kingdom',
    languages: ['English', 'French'],
    languageProficiency: {
      English: 'Native / Fluent',
      French: 'Professional Working',
    },
    skills: [
      'Machine Translation Post-Editing (MTPE)',
      'Proofreading',
      'Bilingual French/English',
      'Terminology Research',
    ],
    experience: 'Oxford graduate and freelance copyeditor & MTPE post-editor in London, UK.',
    role: 'contributor',
    isEmailVerified: true,
    profileStatus: 'Complete',
    avatar: 'ST',
    status: 'active',
    createdAt: '2026-09-01',
  },
];

export const INITIAL_APPLICATIONS: ProjectApplication[] = [
  {
    id: 'app-eg-01',
    projectId: 'proj-arabic-en-001',
    projectName: 'Arabic → English Translation Project',
    projectCategory: 'Translation & Localization',
    userId: 'usr-eg-8821',
    userName: 'Omar Hassan',
    userEmail: 'omar.hassan.trans@gmail.com',
    country: 'Egypt',
    languages: ['Arabic', 'English'],
    languageProficiency: 'Native / Bilingual',
    experience: '5+ years translating literary, commercial, and technical texts from Modern Standard Arabic and Egyptian Arabic to English.',
    skills: [
      'Bilingual Arabic/English',
      'Modern Standard Arabic (MSA)',
      'Context Checking',
      'Terminology Research',
      'Localization QA',
    ],
    status: 'Approved',
    appliedDate: '2026-09-07',
  },
  {
    id: 'app-eg-02',
    projectId: 'proj-arabic-en-001',
    projectName: 'Arabic → English Translation Project',
    projectCategory: 'Translation & Localization',
    userId: 'usr-eg-8822',
    userName: 'Nour Mahmoud',
    userEmail: 'nour.mahmoud.eg@gmail.com',
    country: 'Egypt',
    languages: ['Arabic', 'English'],
    languageProficiency: 'Native / Bilingual',
    experience: 'Experience with Arabic corpora annotation, conversational dataset localization, and English translation.',
    skills: [
      'Bilingual Arabic/English',
      'Modern Standard Arabic (MSA)',
      'Localization QA',
    ],
    status: 'Applied',
    appliedDate: '2026-09-07',
  },
  {
    id: 'app-eg-03',
    projectId: 'proj-arabic-en-001',
    projectName: 'Arabic → English Translation Project',
    projectCategory: 'Translation & Localization',
    userId: 'usr-eg-8823',
    userName: 'Mariam Farouk',
    userEmail: 'mariam.farouk.cairo@gmail.com',
    country: 'Egypt',
    languages: ['Arabic', 'English'],
    languageProficiency: 'Native / Bilingual',
    experience: 'Passionate linguist with expertise in cultural nuance translation and terminological accuracy.',
    skills: [
      'Bilingual Arabic/English',
      'Terminology Research',
      'Context Checking',
    ],
    status: 'Applied',
    appliedDate: '2026-09-07',
  },
  {
    id: 'app-ke-01',
    projectId: 'proj-arabic-en-001',
    projectName: 'Arabic → English Translation Project',
    projectCategory: 'Translation & Localization',
    userId: 'usr-ke-1001',
    userName: 'David Ochieng',
    userEmail: 'david.ochieng.nbo@gmail.com',
    country: 'Kenya',
    languages: ['English', 'Swahili'],
    languageProficiency: 'Professional Working',
    experience: 'Bilingual linguist and AI crowdsource contributor with extensive data QA experience.',
    skills: [
      'Translation & Localization',
      'AI Data Collection',
      'Quality Assurance',
    ],
    status: 'Applied',
    appliedDate: '2026-09-06',
  },
  {
    id: 'app-ke-02',
    projectId: 'proj-arabic-en-001',
    projectName: 'Arabic → English Translation Project',
    projectCategory: 'Translation & Localization',
    userId: 'usr-ke-1002',
    userName: 'Faith Mwangi',
    userEmail: 'faith.mwangi.ling@gmail.com',
    country: 'Kenya',
    languages: ['English', 'Swahili'],
    languageProficiency: 'Native / Bilingual',
    experience: 'Linguistics professional experienced in speech corpora transcription and data review.',
    skills: [
      'Transcription',
      'Quality Assurance',
      'Content Evaluation',
    ],
    status: 'Applied',
    appliedDate: '2026-09-06',
  },
  {
    id: 'app-sa-01',
    projectId: 'proj-arabic-en-001',
    projectName: 'Arabic → English Translation Project',
    projectCategory: 'Translation & Localization',
    userId: 'usr-sa-2001',
    userName: 'Abdulaziz Al-Zahrani',
    userEmail: 'abdulaziz.zahrani@gmail.com',
    country: 'Saudi Arabia',
    languages: ['Arabic', 'English'],
    languageProficiency: 'Native / Bilingual',
    experience: 'Senior Arabic linguist based in Riyadh with direct expertise in Gulf and Modern Standard Arabic translation.',
    skills: [
      'Bilingual Arabic/English',
      'Modern Standard Arabic (MSA)',
      'Terminology Research',
      'Localization QA',
    ],
    status: 'Approved',
    appliedDate: '2026-09-06',
  },
  {
    id: 'app-sa-02',
    projectId: 'proj-arabic-en-001',
    projectName: 'Arabic → English Translation Project',
    projectCategory: 'Translation & Localization',
    userId: 'usr-sa-2002',
    userName: 'Reem Al-Ghamdi',
    userEmail: 'reem.ghamdi.trans@gmail.com',
    country: 'Saudi Arabia',
    languages: ['Arabic', 'English'],
    languageProficiency: 'Native / Bilingual',
    experience: '4 years translating corporate, educational, and digital content between Arabic and English in Jeddah.',
    skills: [
      'Bilingual Arabic/English',
      'Context Checking',
      'Modern Standard Arabic (MSA)',
    ],
    status: 'Applied',
    appliedDate: '2026-09-05',
  },
  {
    id: 'app-pk-01',
    projectId: 'proj-arabic-en-001',
    projectName: 'Arabic → English Translation Project',
    projectCategory: 'Translation & Localization',
    userId: 'usr-pk-3001',
    userName: 'Ayan Khalid',
    userEmail: 'saimaanjum650@gmail.com',
    country: 'Pakistan',
    languages: ['English', 'Urdu'],
    languageProficiency: 'Native / Bilingual',
    experience: 'Experienced localization reviewer and workforce coordinator in Pakistan.',
    skills: [
      'Translation & Localization',
      'Quality Assurance',
      'Content Evaluation',
    ],
    status: 'Approved',
    appliedDate: '2026-09-07',
  },
  {
    id: 'app-pk-02',
    projectId: 'proj-arabic-en-001',
    projectName: 'Arabic → English Translation Project',
    projectCategory: 'Translation & Localization',
    userId: 'usr-pk-3003',
    userName: 'Zunaira Tariq',
    userEmail: 'zunaira.tariq.ling@gmail.com',
    country: 'Pakistan',
    languages: ['English', 'Urdu'],
    languageProficiency: 'Native / Bilingual',
    experience: 'Linguist with 3 years experience in multilingual NLP datasets and sentiment tagging.',
    skills: [
      'Text Annotation',
      'Content Evaluation',
      'Quality Assurance',
    ],
    status: 'Applied',
    appliedDate: '2026-09-06',
  },
  {
    id: 'app-in-01',
    projectId: 'proj-arabic-en-001',
    projectName: 'Arabic → English Translation Project',
    projectCategory: 'Translation & Localization',
    userId: 'usr-in-4001',
    userName: 'Aarav Sharma',
    userEmail: 'aarav.sharma.nlp@gmail.com',
    country: 'India',
    languages: ['English', 'Hindi'],
    languageProficiency: 'Native / Bilingual',
    experience: 'NLP linguistic analyst and professional post-editor in Bengaluru, India.',
    skills: [
      'Translation & Localization',
      'Machine Translation Post-Editing (MTPE)',
      'Quality Assurance',
    ],
    status: 'Applied',
    appliedDate: '2026-09-05',
  },
  {
    id: 'app-in-02',
    projectId: 'proj-arabic-en-001',
    projectName: 'Arabic → English Translation Project',
    projectCategory: 'Translation & Localization',
    userId: 'usr-in-4002',
    userName: 'Priya Patel',
    userEmail: 'priya.patel.ai@gmail.com',
    country: 'India',
    languages: ['English', 'Hindi'],
    languageProficiency: 'Native / Bilingual',
    experience: 'Speech-to-text evaluation specialist and multilingual transcriptionist based in Mumbai.',
    skills: [
      'Localization QA',
      'Transcription',
      'Quality Assurance',
    ],
    status: 'Applied',
    appliedDate: '2026-09-05',
  },
  {
    id: 'app-ae-01',
    projectId: 'proj-arabic-en-001',
    projectName: 'Arabic → English Translation Project',
    projectCategory: 'Translation & Localization',
    userId: 'usr-ae-5001',
    userName: 'Zaid Al-Mansoor',
    userEmail: 'zaid.mansoor.dxb@gmail.com',
    country: 'United Arab Emirates',
    languages: ['Arabic', 'English'],
    languageProficiency: 'Native / Bilingual',
    experience: 'Media & technical translation consultant in Dubai, UAE.',
    skills: [
      'Bilingual Arabic/English',
      'Modern Standard Arabic (MSA)',
      'Quality Assurance',
    ],
    status: 'Approved',
    appliedDate: '2026-09-05',
  },
  {
    id: 'app-ma-01',
    projectId: 'proj-arabic-en-001',
    projectName: 'Arabic → English Translation Project',
    projectCategory: 'Translation & Localization',
    userId: 'usr-ma-8005',
    userName: 'Yassine Berrada',
    userEmail: 'yassine.berrada.casa@gmail.com',
    country: 'Morocco',
    languages: ['Arabic', 'French', 'English'],
    languageProficiency: 'Native / Bilingual',
    experience: 'Trilingual translator in Casablanca, Morocco specializing in Arabic and French-English MTPE.',
    skills: [
      'Bilingual Arabic/English',
      'Modern Standard Arabic (MSA)',
      'Context Checking',
    ],
    status: 'Applied',
    appliedDate: '2026-09-04',
  },
  {
    id: 'app-fr-01',
    projectId: 'proj-french-en-002',
    projectName: 'French → English Machine Translation Project',
    projectCategory: 'Translation & Localization',
    userId: 'usr-fr-8001',
    userName: 'Camille Laurent',
    userEmail: 'camille.laurent.lyon@gmail.com',
    country: 'France',
    languages: ['French', 'English'],
    languageProficiency: 'Native / Bilingual',
    experience: 'Certified French-English translator and MTPE quality specialist in Lyon, France.',
    skills: [
      'Bilingual French/English',
      'Machine Translation Post-Editing (MTPE)',
      'Localization QA',
    ],
    status: 'Approved',
    appliedDate: '2026-09-03',
  },
  {
    id: 'app-ca-01',
    projectId: 'proj-french-en-002',
    projectName: 'French → English Machine Translation Project',
    projectCategory: 'Translation & Localization',
    userId: 'usr-ca-8004',
    userName: 'Liam Tremblay',
    userEmail: 'liam.tremblay.mtl@gmail.com',
    country: 'Canada',
    languages: ['English', 'French'],
    languageProficiency: 'Native / Bilingual',
    experience: 'Bilingual Canadian translator (English/French) and localization QA auditor in Montreal.',
    skills: [
      'Bilingual French/English',
      'Machine Translation Post-Editing (MTPE)',
      'Localization QA',
    ],
    status: 'Approved',
    appliedDate: '2026-09-03',
  },
  {
    id: 'app-uk-01',
    projectId: 'proj-french-en-002',
    projectName: 'French → English Machine Translation Project',
    projectCategory: 'Translation & Localization',
    userId: 'usr-uk-9002',
    userName: 'Sophie Taylor',
    userEmail: 'sophie.taylor.uk@gmail.com',
    country: 'United Kingdom',
    languages: ['English', 'French'],
    languageProficiency: 'Native / Bilingual',
    experience: 'Oxford graduate and freelance copyeditor & MTPE post-editor in London, UK.',
    skills: [
      'Machine Translation Post-Editing (MTPE)',
      'Proofreading',
      'Bilingual French/English',
    ],
    status: 'Applied',
    appliedDate: '2026-09-02',
  },
  {
    id: 'app-us-01',
    projectId: 'proj-french-en-002',
    projectName: 'French → English Machine Translation Project',
    projectCategory: 'Translation & Localization',
    userId: 'usr-us-9001',
    userName: 'Marcus Bennett',
    userEmail: 'marcus.bennett.data@gmail.com',
    country: 'United States',
    languages: ['English', 'Spanish'],
    languageProficiency: 'Native / Bilingual',
    experience: 'Senior Data Evaluation Specialist in Austin, Texas. 5+ years reviewing LLM RLHF corpora.',
    skills: [
      'Quality Assurance',
      'Content Evaluation',
      'AI Prompt Evaluation',
    ],
    status: 'Applied',
    appliedDate: '2026-09-02',
  },
];

export const INITIAL_PAYMENT_METHODS: PaymentMethod[] = [];
export const INITIAL_EARNINGS: ContributorEarning[] = [];
export const INITIAL_WITHDRAWALS: WithdrawalRequest[] = [];
export const INITIAL_PROJECT_UPDATES: ProjectUpdate[] = [];
export const INITIAL_NOTIFICATIONS: NotificationItem[] = [];

// 18 Work taxonomies according to SRS v1.1
export const ALL_CATEGORIES = [
  {
    name: 'Translation & Localization',
    description: 'Translate, localize, and quality-check content between language pairs with human nuances.',
    icon: 'Languages',
    count: 1,
  },
  {
    name: 'Transcription',
    description: 'Convert speech, conversations, and audio/video files into clean, timestamped text.',
    icon: 'Headphones',
    count: 0,
  },
  {
    name: 'Audio Annotation',
    description: 'Analyze acoustic events, speaker diarization, emotions, and sound classification.',
    icon: 'Mic',
    count: 0,
  },
  {
    name: 'Text Annotation',
    description: 'Entity recognition, sentiment analysis, topic categorization, and linguistic tagging.',
    icon: 'FileText',
    count: 0,
  },
  {
    name: 'Image Annotation',
    description: 'Bounding boxes, polygon segmentation, keypoints, and visual defect identification.',
    icon: 'Image',
    count: 0,
  },
  {
    name: 'Video Annotation',
    description: 'Object tracking across frames, action recognition, scene transitions, and event timing.',
    icon: 'Video',
    count: 0,
  },
  {
    name: 'AI Data Collection',
    description: 'Collect rich real-world voice samples, images, documents, and dialogue recordings.',
    icon: 'FolderPlus',
    count: 0,
  },
  {
    name: 'Data Labeling',
    description: 'Categorize datasets, assign multi-class labels, and structure raw training data.',
    icon: 'Tag',
    count: 0,
  },
  {
    name: 'LLM Evaluation',
    description: 'Compare multi-model responses, audit truthfulness, reasoning quality, and RLHF criteria.',
    icon: 'Bot',
    count: 0,
  },
  {
    name: 'AI Model Evaluation',
    description: 'Stress-test AI outputs against benchmarks, identify hallucinations, and score accuracy.',
    icon: 'Cpu',
    count: 0,
  },
  {
    name: 'Linguistic Evaluation',
    description: 'Expert syntax, morphology, pragmatics, naturalness, and regional dialect validation.',
    icon: 'BookOpen',
    count: 0,
  },
  {
    name: 'Search / Relevance Evaluation',
    description: 'Judge query intent, web search result utility, content freshness, and domain relevance.',
    icon: 'Search',
    count: 0,
  },
  {
    name: 'Question & Answer (KQA/QA)',
    description: 'Formulate questions, verify knowledge graph ground-truth answers, and test QA engines.',
    icon: 'HelpCircle',
    count: 0,
  },
  {
    name: 'Speech / ASR Projects',
    description: 'Automatic speech recognition correction, phoneme alignment, and pronunciation testing.',
    icon: 'Volume2',
    count: 0,
  },
  {
    name: 'Prompt Evaluation',
    description: 'Assess prompt effectiveness, user intent alignment, and safety instruction compliance.',
    icon: 'MessageSquare',
    count: 0,
  },
  {
    name: 'Content Evaluation',
    description: 'Review digital content for community guidelines, misinformation, safety, and suitability.',
    icon: 'ShieldCheck',
    count: 0,
  },
  {
    name: 'Data Quality Assurance',
    description: 'Senior audit, consensus scoring, error categorization, and contributor feedback loops.',
    icon: 'CheckCircle2',
    count: 0,
  },
  {
    name: 'Other AI/Data Projects',
    description: 'Custom workflows, bespoke multi-modal tasks, and specialized enterprise data pipelines.',
    icon: 'Sparkles',
    count: 0,
  },
] as const;
